"""add scheduling group

Revision ID: 0b6877d2a10d
Revises: 820b3bd13910
Create Date: 2021-10-13 01:43:31.319534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b6877d2a10d"
down_revision = "820b3bd13910"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crontabschedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("minute", sa.String(length=64), nullable=True),
        sa.Column("hour", sa.String(length=64), nullable=True),
        sa.Column("day_of_week", sa.String(length=64), nullable=True),
        sa.Column("day_of_month", sa.String(length=64), nullable=True),
        sa.Column("month_of_year", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crontabschedule")),
    )
    op.create_table(
        "intervalschedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("every", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=24), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intervalschedule")),
    )
    op.create_table(
        "scheduleentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("task", sa.String(length=255), nullable=True),
        sa.Column("interval_id", sa.Integer(), nullable=True),
        sa.Column("crontab_id", sa.Integer(), nullable=True),
        sa.Column("arguments", sa.String(length=255), nullable=True),
        sa.Column("keyword_arguments", sa.String(length=255), nullable=True),
        sa.Column("queue", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=255), nullable=True),
        sa.Column("routing_key", sa.String(length=255), nullable=True),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("total_run_count", sa.Integer(), nullable=True),
        sa.Column("date_changed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crontab_id"],
            ["crontabschedule.id"],
            name=op.f("fk_scheduleentry_crontab_id_crontabschedule"),
        ),
        sa.ForeignKeyConstraint(
            ["interval_id"],
            ["intervalschedule.id"],
            name=op.f("fk_scheduleentry_interval_id_intervalschedule"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduleentry")),
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("scheduleentry")
    op.drop_table("intervalschedule")
    op.drop_table("crontabschedule")
    # ### end Alembic commands ###
