"""added onupdate

Revision ID: 8b20a39be7e0
Revises: b13cc6122023
Create Date: 2021-12-11 18:52:14.037278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b20a39be7e0'
down_revision = 'b13cc6122023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_schedule_interval_id_intervalschedule', 'schedule', type_='foreignkey')
    op.drop_constraint('fk_schedule_crontab_id_crontabschedule', 'schedule', type_='foreignkey')
    op.create_foreign_key(op.f('fk_schedule_crontab_id_crontabschedule'), 'schedule', 'crontabschedule', ['crontab_id'], ['id'])
    op.create_foreign_key(op.f('fk_schedule_interval_id_intervalschedule'), 'schedule', 'intervalschedule', ['interval_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schedule_interval_id_intervalschedule'), 'schedule', type_='foreignkey')
    op.drop_constraint(op.f('fk_schedule_crontab_id_crontabschedule'), 'schedule', type_='foreignkey')
    op.create_foreign_key('fk_schedule_crontab_id_crontabschedule', 'schedule', 'crontabschedule', ['crontab_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_schedule_interval_id_intervalschedule', 'schedule', 'intervalschedule', ['interval_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
