"""Added unique constraint to canvas & schedule name

Revision ID: d78a37afd4ed
Revises: 8b20a39be7e0
Create Date: 2021-12-30 21:54:29.792988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78a37afd4ed'
down_revision = '8b20a39be7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_canvas_name'), 'canvas', ['name'])
    op.create_unique_constraint(op.f('uq_schedule_name'), 'schedule', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_schedule_name'), 'schedule', type_='unique')
    op.drop_constraint(op.f('uq_canvas_name'), 'canvas', type_='unique')
    # ### end Alembic commands ###
