"""Aadded cascade delete to crontab/interval fk

Revision ID: d87270ee40fa
Revises: 56530fb4771e
Create Date: 2021-12-02 04:03:07.689740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d87270ee40fa"
down_revision = "56530fb4771e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("canvas_id", sa.Integer(), nullable=True),
        sa.Column("interval_id", sa.Integer(), nullable=True),
        sa.Column("crontab_id", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("total_run_count", sa.Integer(), nullable=True),
        sa.Column("date_changed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["canvas_id"], ["canvas.id"], name=op.f("fk_schedule_canvas_id_canvas")
        ),
        sa.ForeignKeyConstraint(
            ["crontab_id"],
            ["crontabschedule.id"],
            name=op.f("fk_schedule_crontab_id_crontabschedule"),
        ),
        sa.ForeignKeyConstraint(
            ["interval_id"],
            ["intervalschedule.id"],
            name=op.f("fk_schedule_interval_id_intervalschedule"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule")),
    )
    op.drop_table("scheduleentry")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduleentry",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("signature_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("interval_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("crontab_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "last_run_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("total_run_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "date_changed", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["crontab_id"],
            ["crontabschedule.id"],
            name="fk_scheduleentry_crontab_id_crontabschedule",
        ),
        sa.ForeignKeyConstraint(
            ["interval_id"],
            ["intervalschedule.id"],
            name="fk_scheduleentry_interval_id_intervalschedule",
        ),
        sa.ForeignKeyConstraint(
            ["signature_id"], ["canvas.id"], name="fk_scheduleentry_signature_id_canvas"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_scheduleentry"),
    )
    op.drop_table("schedule")
    # ### end Alembic commands ###
